# palette = 'catppuccin_latte'
# palette = 'catppuccin_frappe'
# palette = 'catppuccin_macchiato'
palette = 'catppuccin_mocha'

format = """
($status\n)\
[](color_mantle)\
$os\
$username\
[ ](bg:color_mantle fg:color_mantle)\
${custom.is_folder_config}\
$directory\
[ ](fg:color_mantle bg:color_mantle)\
$git_branch\
$git_status\
$git_commit\
[ ](fg:color_mantle bg:color_mantle)\
$c\
${custom.cpp-gcc}\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$lua\
$python\
$cmake\
$docker_context\
\
$meson\
${env_var.shell}\
$shell\
${custom.nvim}\
[ ](fg:color_mantle bg:color_mantle)\
$cmd_duration\
[ ](fg:color_mantle)\
$line_break$character"""

add_newline = true

[os]
disabled = true
style = "bg:color_mantle fg:color_text"

[cmd_duration]
min_time = 1_000
show_notifications = false
min_time_to_notify = 10_000

show_milliseconds = true
format = '[$duration ]($style)'
style = 'fg:color_pink bg:color_mantle'



[custom.is_folder_config]
disabled = true
when = "echo $PWD | grep -q '/.config'"
symbol = ' '
format = '[$symbol]($style)'
style = 'fg:color_blue bg:color_mantle'

[env_var.shell]
disabled = true
symbol = ''
variable = 'SHELL'
format = '[($symbol $env_value )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[shell]
disabled = true

[custom.nvim]
disabled = true
when = "echo $PWD | grep -q '.config/nvim'"
symbol = ' '
format = '[$symbol($output )]($style)'
style = 'fg:color_lavender bg:color_mantle'
command = "nvim --version | head -n 1 | tr ' ' '\n' | tail -n 1"

[meson]
symbol = 'Meson: '
format = '[$symbol(\($project\) )]($style)'
style = 'fg:color_lavender bg:color_mantle'



[directory]
truncate_to_repo = true
format = '[([$read_only ]($style fg:color_red))$path ]($style)'
style = 'fg:color_text bg:color_mantle'
truncation_length = 5
read_only = ''

[git_branch]
# symbol = ''
symbol = ''
format = '[$symbol $branch(:$remote_branch) ]($style)'
style = 'fg:color_red bg:color_mantle'

[git_status]
disabled = true

[git_commit]
disabled = false
only_detached = false
tag_disabled = false
format = '[$tag #$hash ]($style)'
style = 'fg:color_red bg:color_mantle'
commit_hash_length = 4
tag_symbol = ''



[c]
symbol = 'gcc: '
format = '[$symbol($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[custom.cpp-gcc]
symbol = 'g++: '
format = '[$symbol($output )]($style)'
style = 'fg:color_lavender bg:color_mantle'
detect_extensions = ['cpp', 'c++', 'hpp', 'h++']
command = "g++ --version | tr ' ' '\n' | head -n 3 | tail -n 1"

[docker_context]
symbol = ' '
format = '[$symbol$context ]($style)'
style = 'fg:color_blue bg:color_mantle'

[golang]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[lua]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[nodejs]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[python]
symbol = ' '
format =  '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[rust]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'

[cmake]
format = '[$symbol($version )]($style)'
style = 'fg:color_lavender bg:color_mantle'






[line_break]
disabled = false

[status]
disabled = false
style = 'fg:color_text bg:color_base'
format = """
[\
(Exit code: [$maybe_int]($style fg:color_red))\
(Exit status: [$common_meaning]($style fg:color_peach))\
(Signal: [$signal_name]($style fg:color_yellow))]\
($style)\
"""

[character]
format = ' '
disabled = false

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "



[palettes.catppuccin_latte]
color_pink =      "#ea76cb"
color_red =       "#d20f39"
color_peach =     "#fe640b"
color_yellow =    "#df8e1d"
color_blue =      "#1e66f5"
color_lavender =  "#7287fd"
color_text = "#4c4f69"
color_base = "#eff1f5"
color_mantle = "#e6e9ef"

[palettes.catppuccin_frappe]
color_pink =      "#f4b8e4"
color_red =       "#e78284"
color_peach =     "#ef9f76"
color_yellow =    "#e5c890"
color_blue =      "#8caaee"
color_lavender =  "#babbf1"
color_text = "#c6d0f5"
color_base = "#303446"
color_mantle = "#292c3c"

[palettes.catppuccin_macchiato]
color_pink =      "#f5bde6"
color_red =       "#ed8796"
color_peach =     "#f5a97f"
color_yellow =    "#eed49f"
color_blue =      "#8aadf4"
color_lavender =  "#b7bdf8"
color_text = "#cad3f5"
color_base = "#24273a"
color_mantle = "#1e2030"

[palettes.catppuccin_mocha]
color_pink =      "#f5c2e7"
color_red =       "#f38ba8"
color_peach =     "#fab387"
color_yellow =    "#f9e2af"
color_blue =      "#89b4fa"
color_lavender =  "#b4befe"
color_text = "#cdd6f4"
color_base = "#1e1e2e"
color_mantle = "#181825"
