# palette = 'catppuccin_latte'
# palette = 'catppuccin_frappe'
# palette = 'catppuccin_macchiato'
palette = 'kanagawa_dark'

format = """
($status\n)\
[](color_bg)\
$os\
$username\
[ ](bg:color_bg fg:color_bg)\
${custom.is_folder_config}\
$directory\
[ ](fg:color_bg bg:color_bg)\
$git_branch\
$git_status\
$git_commit\
[ ](fg:color_bg bg:color_bg)\
$c\
${custom.cpp-gcc}\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$lua\
$python\
$cmake\
$docker_context\
\
$meson\
${env_var.shell}\
$shell\
${custom.nvim}\
[ ](fg:color_bg bg:color_bg)\
$cmd_duration\
[ ](fg:color_bg)\
$line_break$character"""

add_newline = true

[os]
disabled = true
style = "bg:color_bg fg:color_fg"

[cmd_duration]
min_time = 1_000
show_notifications = false
min_time_to_notify = 10_000

show_milliseconds = true
format = '[$duration ]($style)'
style = 'fg:color_fg_light bg:color_bg'



[custom.is_folder_config]
disabled = true
when = "echo $PWD | grep -q '/.config'"
symbol = ' '
format = '[$symbol]($style)'
style = 'fg:color_blue bg:color_bg'

[env_var.shell]
disabled = true
symbol = ''
variable = 'SHELL'
format = '[($symbol $env_value )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'

[shell]
disabled = true

[custom.nvim]
disabled = true
when = "echo $PWD | grep -q '.config/nvim'"
symbol = ' '
format = '[$symbol($output )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'
command = "nvim --version | head -n 1 | tr ' ' '\n' | tail -n 1"

[meson]
symbol = 'Meson: '
format = '[$symbol(\($project\) )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'



[directory]
truncate_to_repo = true
format = '[([$read_only ]($style fg:color_fail))$path ]($style)'
style = 'fg:color_fg bg:color_bg'
truncation_length = 5
read_only = ''

[git_branch]
# symbol = ''
symbol = ''
format = '[$symbol $branch(:$remote_branch) ]($style)'
style = 'fg:color_fg_git bg:color_bg'

[git_status]
disabled = true

[git_commit]
disabled = false
only_detached = false
tag_disabled = false
format = '[$tag #$hash ]($style)'
style = 'fg:color_fg_git bg:color_bg'
commit_hash_length = 4
tag_symbol = ''



[c]
symbol = 'gcc: '
format = '[$symbol($version )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'

[custom.cpp-gcc]
symbol = 'g++: '
format = '[$symbol($output )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'
detect_extensions = ['cpp', 'c++', 'hpp', 'h++']
command = "g++ --version | tr ' ' '\n' | head -n 3 | tail -n 1"

[docker_context]
symbol = ' '
format = '[$symbol$context ]($style)'
style = 'fg:color_blue bg:color_bg'

[golang]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'

[lua]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'

[nodejs]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'

[python]
symbol = ' '
format =  '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'

[rust]
symbol = ''
format = '[$symbol ($version )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'

[cmake]
format = '[$symbol($version )]($style)'
style = 'fg:color_fg_recognized bg:color_bg'






[line_break]
disabled = false

[status]
disabled = false
style = 'fg:color_fg bg:color_bg_terminal'
format = """
[\
(Exit code: [$maybe_int]($style fg:color_fail))\
(Exit status: [$common_meaning]($style fg:color_fg_warn))\
(Signal: [$signal_name]($style fg:color_fg_info))]\
($style)\
"""

[character]
format = ' '
disabled = false

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "



[palettes.kanagawa_dark]
color_bg = "#16161d"
color_bg_terminal = "#1f1f28"
color_fg = "#c8c093"
color_fg_light = "#938aa9"
color_fg_recognized = "#7fb4ca"
color_fg_git = "#c34043"
color_fg_fail = "#e82424"
color_fg_warn = "#ff9e3b" #ffa066
color_fg_info = "#6a9589"
color_blue = "#7e9cd8"
